[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
project-root = "0.2.2"
tracing = "0.1"
tracing-subscriber = "0.3.18"
nom = "7.1.3"
